version: '3'

services:
  kafka:
    image: apache/kafka:3.7.0
    ports:
      - "9092:9092"

  postgres:
    image: postgres:13
    ports:
      - "6543:5432"
    environment:
      POSTGRES_PASSWORD: password
